sudo: required
services:
  - docker

before_install:
  - docker build -t "$DOCKER_ID"/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true $DOCKER_ID/react-test npm test

after_success:
  - docker build -t "$DOCKER_ID"/multi-client ./client
  - docker build -t "$DOCKER_ID"/multi-nginx ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server
  - docker build -t "$DOCKER_ID"/multi-worker ./worker-go
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push "$DOCKER_ID"/multi-client
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-multi-legacy"
  environment: "Dockermultilegacy-env"
  bucket_name: "elasticbeanstalk-us-west-2-719272187394"
  bucket_path: "docker-multi-legacy"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"